<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-del-projecto-equipo175-rva-a01378921-rrm-a01793108/blob/main/Equipo_175_TrabajoGrupo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semana 1

Materia: Ciencia y anallítica de datos

Nombre y matrícula de miembros del equipo 175:

Roberto Vega Alanis (A01378921)

Jhonathan Ricardo Robayo Martínez (A01793108)

**Introducción**

El conjunto de datos seleccionado es una muestra representativa de un registro de transacciones dentro de la cadena de suministro de una empresa de retail.

En una empresa, cadena de suministro es una de las áreas que generalmente cuenta con la mayor cantidad de datos y que, al mismo, es aquella que irónicamente suele desaprovacharlos más.

Esta misma área engloba las actividades de manufactura y distribución de producto, mismas en las que bien es sabido radican la mayor parte de oportunidades de eficientización.

El conjunto de datos seleccionado, por lo tanto, está destiunado a resover un problema tanto económico, al buscar reducir cotos aumentando la eficiencia de los sistemas de distribución y, por lo tanto, ecológico al buscar brindar el mismo servicio haciendo uso una menor cantidad de recursos.

**Respuestas:**

1. El nombre que caracteriza el conjunto de datos:
> DataCoSupplyChainDataset

2. La organización que lo generó
> DataCo Global (https://www.crunchbase.com/organization/dataco-77ff)

3. Incluya un enlace de Internet donde se puedan descargar el base de datos en línea:
> https://data.mendeley.com/datasets/8gx2fvg2k6/5 (fuente adicional: https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis)

4. Describe el conjunto de datos. ¿Qué datos contiene?

> Contiene información sobre retail, desde la petición del producto hasta su llegada; si el pedido fue cancelado o no; que tipo de membresía de envío tienen los clientes; que medio de pago utilizan; el lugar de entrega, que identifica desde el país hasta algunas de sus regiones; contiene además el valor monetario de los pedios; el beneficio y categoría del pedido, por mencionar algunas variables. 

5. ¿Cuáles son algunas de las preguntas de investigación que podría responder con estos datos? Enumere al menos OCHO (no responda las preguntas).

> Las preguntas de investigación que podemos resolver son varias y dependerán del objetivo que se tenga, pues como ya se mencionó, los datos tienen algunas desagregaciones. Por lo cual, podríamos crear varios modelos generales y luego focalizarlos. Por ejemplo, pasariamos a estudiar la cancelación de pedidos o preferencias de membresias en general y luego analizaríamos que particularidad existe dentro de los distintos paises o medios de pago.

Algunos ejemplos generales son:

   * Probabilidad de cancelación de un pedido.
   * Prdección de si el envío llegará a tiempo.
   * Predicción de los días de retraso de la entrega.
   * Predicción del nivel de ganancias.
   * Predección del nivel de ventas.
   * Predicción del tipo de membresía para futuros o actuales clientes (eligendo la más rentable, se buscaría identificar que clientes que no la tienen para recomendarles).
   * Recomendación de medios de pago (eligiendo el más rentable, se buscaría identificar que clientes que no tienen este servicio para recomendarles).
   * Identificar qué productos, paises o montos tienen retrasos, para generar estrategias.
   * Predecir los días de retraso para establecer el tiempo que se demoraría la entrega.
   * Predecir la probabilidad de compra de productos para realizar abastecimientos.
   * Generar un recomendador de productos, pero tal vez sea necesario tener información complementaria.

Es notable que algunas de las preguntas van a generar resultados que luego pueden ser utilizados para responder otras preguntas.

6. ¿Qué actor (empresa, sector de la sociedad, organismo descentralizado, gobierno, etc.) estaría interesado en las preguntas mencionadas que identificó?

> Las empresas que se interesarían por estas respuestas serían:

 * Retail (Walmart, Soriana, Chedraui)
 * Cualquier empresa con esquema de venta DTC (Direct To Customer) (PepsiCo)
 * Tiendas en línea (Mercado Libre, Amazon)
 * Empresas de paqueterías (UPS, DHL)

## Ingesta de datos

In [ ]:
# Librarías
import pandas as pd

In [ ]:
delivery = pd.read_csv("DataCoSupplyChainDataset.csv", sep =",", encoding ='latin1')
delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [ ]:
delivery.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class